// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Orders
    {
        /// <summary>
        /// Initializes a new instance of the Orders class.
        /// </summary>
        public Orders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Orders class.
        /// </summary>
        public Orders(int? orderId = default(int?), string customerId = default(string), int? employeeId = default(int?), System.DateTime? orderDate = default(System.DateTime?), System.DateTime? requiredDate = default(System.DateTime?), System.DateTime? shippedDate = default(System.DateTime?), int? shipVia = default(int?), double? freight = default(double?), string shipName = default(string), string shipAddress = default(string), string shipCity = default(string), string shipRegion = default(string), string shipPostalCode = default(string), string shipCountry = default(string), Customers customer = default(Customers), Employees employee = default(Employees), Shippers shipViaNavigation = default(Shippers), IList<OrderDetails> orderDetails = default(IList<OrderDetails>))
        {
            OrderId = orderId;
            CustomerId = customerId;
            EmployeeId = employeeId;
            OrderDate = orderDate;
            RequiredDate = requiredDate;
            ShippedDate = shippedDate;
            ShipVia = shipVia;
            Freight = freight;
            ShipName = shipName;
            ShipAddress = shipAddress;
            ShipCity = shipCity;
            ShipRegion = shipRegion;
            ShipPostalCode = shipPostalCode;
            ShipCountry = shipCountry;
            Customer = customer;
            Employee = employee;
            ShipViaNavigation = shipViaNavigation;
            OrderDetails = orderDetails;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderId")]
        public int? OrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "employeeId")]
        public int? EmployeeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderDate")]
        public System.DateTime? OrderDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requiredDate")]
        public System.DateTime? RequiredDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shippedDate")]
        public System.DateTime? ShippedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipVia")]
        public int? ShipVia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "freight")]
        public double? Freight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipName")]
        public string ShipName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipAddress")]
        public string ShipAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipCity")]
        public string ShipCity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipRegion")]
        public string ShipRegion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipPostalCode")]
        public string ShipPostalCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipCountry")]
        public string ShipCountry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customer")]
        public Customers Customer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "employee")]
        public Employees Employee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipViaNavigation")]
        public Shippers ShipViaNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderDetails")]
        public IList<OrderDetails> OrderDetails { get; set; }

    }
}
