// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Shippers
    {
        /// <summary>
        /// Initializes a new instance of the Shippers class.
        /// </summary>
        public Shippers()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Shippers class.
        /// </summary>
        public Shippers(int? shipperId = default(int?), string companyName = default(string), string phone = default(string), IList<Orders> orders = default(IList<Orders>))
        {
            ShipperId = shipperId;
            CompanyName = companyName;
            Phone = phone;
            Orders = orders;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipperId")]
        public int? ShipperId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "companyName")]
        public string CompanyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orders")]
        public IList<Orders> Orders { get; set; }

    }
}
